db_name         = "fppdb"
subscription_id = "80d37f3a-a7f6-405b-a0d0-e2d362572306"
rg_name         = "FPP-RG"
location        = "westus3"
sql_server_name = "fawazpranaypranavserver"
sql_admin_user  = "adminuser"
sql_admin_pass  = "abcd@1234"
resource_group_name = "FPP-RG"
